client_config_backend: settings
client_config:
  client_id: 955573250108-ld7kijiibrl0spg7jsg0ifukm60j8oaj.apps.googleusercontent.com
  client_secret: R6lTMSSDIrEktyctIeqj6uv1

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install